apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-console-operator
  name: telemetry
spec:
  data:
    SEGMENT_API_KEY: BnuS1RP39EmLQjP21ko67oDjhbl9zpNU
    SEGMENT_API_HOST: console.redhat.com/connections/api/v1
    SEGMENT_JS_HOST: console.redhat.com/connections/cdn